window.prompts = {
  mood: {
    title: "Mood modifiers",
    description: "Happy/Sad keywords",
    prefix: " ",
    suffix: " ",
    items: [
      {
        title: "Positive+",
        description: "Positive mood, Low Energy 🙂",
        type: "random",
        variants: [
          "light",
          "peaceful",
          "calm",
          "serene",
          "soothing",
          "relaxed",
          "placid",
          "comforting",
          "cosy",
          "tranquil",
          "quiet",
          "pastel",
          "delicate",
          "graceful",
          "subtle",
          "balmy",
          "mild",
          "ethereal",
          "elegant",
          "tender",
          "soft",
          "light",
        ],
      },
      {
        title: "Positive++",
        description: "Positive mood, High Energy 😆",
        type: "random",
        variants: [
          "bright",
          "vibrant",
          "dynamic",
          "spirited",
          "vivid",
          "lively",
          "energetic",
          "colorful",
          "joyful",
          "romantic",
          "expressive",
          "bright",
          "rich",
          "kaleidoscopic",
          "psychedelic",
          "saturated",
          "ecstatic",
          "brash",
          "exciting",
          "passionate",
          "hot",
        ],
      },
      {
        title: "Negative-",
        description: "Negative mood, Low Energy 😢",
        type: "random",
        variants: [
          "muted",
          "bleak",
          "funereal",
          "somber",
          "melancholic",
          "mournful",
          "gloomy",
          "dismal",
          "sad",
          "pale",
          "washed-out",
          "desaturated",
          "grey",
          "subdued",
          "dull",
          "dreary",
          "depressing",
          "weary",
          "tired",
        ],
      },
      {
        title: "Negative--",
        type: "random",
        description: "Negative mood, High Energy 😭",
        variants: [
          "dark",
          "ominous",
          "threatening",
          "haunting",
          "forbidding",
          "gloomy",
          "stormy",
          "doom",
          "apocalyptic",
          "sinister",
          "shadowy",
          "ghostly",
          "unnerving",
          "harrowing",
          "dreadful",
          "frightful",
          "shocking",
          "terror",
          "hideous",
          "ghastly",
          "terrifying",
        ],
      },
      {
        title: "Quality Enhancers",
        type: "random",
        description: `Click a few times to get high quality results,"Award-Winning Art", "Trending on ArtStation", "trending on behance", "4k", "8k",
                "Photorealistic", "Unreal Engine", "Detailed", "Award Winning", "sharp" `,
        variants: [
          "Award-Winning Art",
          "Trending on ArtStation",
          "trending on behance",
          "4k",
          "8k",
          "Photorealistic",
          "Unreal Engine",
          "Detailed",
          "Award Winning",
          "sharp",
        ],
      },
    ],
  },
  vibes: {
    title: "Vibes and styles",
    description: "Vibes keywords",
    prefix: " ",
    suffix: " style ",
    items: [
      {
        title: "Vaporware",
        img: "vaporware.jpg",
        description: "Vaporwavre style",
        type: "toggle",
        variants: ["neon", "pink", "blue", "geometric", "futuristic", "'80s"],
      },
      {
        title: "Post-Apocalyptic",
        img: "post-apocalyptic.jpg",
        description: "Post apocalyptic style",
        type: "toggle",
        variants: ["grey", "desolate", "stormy", "fire", "decay"],
      },
      {
        title: "Gothic ,Fantasy",
        img: "gothic.jpg",
        description:
          "Gothic fantrasy style, stone, dark, lush, nature, mist, mystery, angular",
        type: "toggle",
        variants: [
          "stone",
          "dark",
          "lush",
          "nature",
          "mist",
          "mystery",
          "angular",
        ],
      },
      {
        title: "Cybernetic, sci-fi",
        img: "cybernetic.jpg",
        description: "Cybernetic, sci-fi: glows, greens, metals, armor, chrome",
        type: "toggle",
        variants: ["glows, greens, metals, armor", "chrome"],
      },
      {
        title: "Steampunk",
        img: "steampunk.jpg",
        description: "Steampunk: gold, copper, brass, Victoriana",
        type: "toggle",
        variants: ["gold", "copper", "brass", "Victoriana"],
      },
      {
        title: "Memphis",
        img: "memphis.jpg",
        description:
          "Memphis, Memphis Group, 1980s,bold, kitch, colourful, shapes",
        type: "toggle",
        variants: [
          "Memphis",
          "Memphis Group",
          "1980s",
          "bold",
          "kitch",
          "colourful",
          " shapes",
        ],
      },
      {
        title: "Dieselpunk",
        img: "dieselpunk.jpg",
        description:
          "Dieselpunk, grimy, steel, oil, '50s,mechanised, punk cousin of steampnk",
        type: "toggle",
        variants: [
          "grimy",
          "steel",
          "oil",
          "'50s",
          "mechanised",
          "punk cousin of steampnk",
        ],
      },
      {
        title: "Afrofuturism",
        img: "afrofuturism.jpg",
        description: "Afrofuturism: futuristic, and African!",
        type: "toggle",
        variants: ["afrofuturism"],
      },
      {
        title: "Cyberpunk",
        img: "cyberpunk.jpg",
        description: "Cyberpunk, 1990s, dyed hair,spiky, graphic elements",
        type: "toggle",
        variants: [
          "cyberpunk",
          "1990s",
          "dyed hair",
          "spiky",
          "graphic elements",
        ],
      },
      {
        title: "Biopunk, organic",
        img: "biopunk.jpg",
        description:
          "Biopunk, organic, greens,slimes, plants, futuristic, weird",
        type: "toggle",
        variants: ["greens", "slimes", "plants", "futuristic", "weird"],
      },
    ],
  },
  "Illustration - digital media": {
    title: "Illustration - digital media",
    description: "Helps create gorgerous high quality prints",
    prefix: " ",
    suffix: " ",
    items: [
      {
        title: "vector art",
        prefix: "2d digital ",
        img: "CleanShot 2022-07-14 at 21.59.15@2x.jpg",
        description: "vector art",
        type: "toggle",
        variants: ["vector art"],
      },
      {
        title: "digital painting",
        img: "CleanShot 2022-07-14 at 22.03.03@2x.jpg",
        description: "digital painting",
        type: "toggle",
        variants: ["digital painting"],
      },
      {
        title: "low poly",
        img: "CleanShot 2022-07-14 at 22.00.13@2x.jpg",
        description: "low poly",
        type: "toggle",
        variants: ["low poly"],
      },
      {
        title: "layered paper",
        img: "CleanShot 2022-07-14 at 22.00.29@2x.jpg",
        description: "layered paper",
        type: "toggle",
        variants: ["layered paper"],
      },
      {
        title: "sticker illustration",
        img: "CleanShot 2022-07-14 at 22.00.57@2x.jpg",
        description: "sticker illustration",
        type: "toggle",
        variants: ["sticker illustration"],
      },
      {
        title: "storybook",
        img: "CleanShot 2022-07-14 at 22.01.33@2x.jpg",
        description: "storybook",
        type: "toggle",
        variants: ["storybook"],
      },
      {
        title: "screen printing",
        img: "CleanShot 2022-07-14 at 22.02.10@2x.jpg",
        description: "screen printing",
        type: "toggle",
        variants: ["screen printing"],
      },
      {
        title: "knolling",
        img: "CleanShot 2022-07-19 at 10.11.05@2x.jpg",
        description: "knolling",
        type: "toggle",
        variants: ["knolling"],
      },
    ],
  },
  "Illustration - 3D + Textured": {
    title: "Illustration - 3D + Textured",
    description: "Gorgeous 3d models",
    prefix: " ",
    suffix: " ",
    items: [
      {
        title: "isometric 3D",
        img: "CleanShot 2022-07-14 at 22.12.48@2x.jpg",
        description: "isometric 3D",
        type: "toggle",
        variants: ["isometric 3D"],
      },
      {
        title: "3D render",
        img: "CleanShot 2022-07-14 at 22.14.12@2x.jpg",
        description:
          "3D render, houdini 3D, octane 3D, ZBrush, Maya, Cinema 4D, Blender",
        type: "toggle",
        variants: [
          "3D render",
          "houdini 3D",
          "octane 3D",
          "ZBrush",
          "Maya",
          "Cinema 4D",
          "Blender",
        ],
      },
      {
        title: "claymation",
        img: "CleanShot 2022-07-14 at 22.14.29@2x.jpg",
        description: "claymation, aardman animation",
        type: "toggle",
        variants: ["claymation", "aardman animation"],
      },
      {
        title: "felt pieces",
        img: "CleanShot 2022-07-14 at 22.14.40@2x.jpg",
        description: "felt pieces",
        type: "toggle",
        variants: ["felt pieces"],
      },
      {
        title: "fabric patterns",
        img: "CleanShot 2022-07-14 at 22.15.38@2x.jpg",
        description: "fabric patterns",
        type: "toggle",
        variants: ["fabric patterns"],
      },
      {
        title: "tatoo art",
        img: "CleanShot 2022-07-14 at 22.15.52@2x.jpg",
        description: "tatoo",
        type: "toggle",
        variants: ["tatoo", "tatoo art"],
      },
      {
        title: "screenshot",
        img: "CleanShot 2022-07-14 at 22.25.03@2x.jpg",
        description: "screenshot from game (year), console",
        type: "toggle",
        variants: [
          "screenshot from final fantasy (2019)",
          "screenshot from cyberpunk (2020)",
        ],
      },
      {
        title: "collage",
        img: "CleanShot 2022-07-14 at 22.02.46@2x.jpg",
        description: "collage",
        type: "toggle",
        variants: ["collage"],
      },
    ],
  },
  "Illustration - character + cartoon": {
    title: "Illustration - character + cartoon",
    description: "Cartoonish characters",
    prefix: " ",
    suffix: " ",
    items: [
      {
        title: "pixar",
        img: "CleanShot 2022-07-14 at 22.26.30@2x.jpg",
        description: "pixar",
        type: "toggle",
        variants: ["pixar"],
      },
      {
        title: "studio ghibli",
        img: "CleanShot 2022-07-14 at 22.26.41@2x.jpg",
        description: "studio ghibli",
        type: "toggle",
        variants: ["studio ghibli", "hayayo miyazaki"],
      },
      {
        title: "anime",
        img: "CleanShot 2022-07-14 at 22.28.06@2x.jpg",
        description: "anime, manga, manga art",
        type: "toggle",
        variants: ["anime", "manga"],
      },

      {
        title: "comic book art",
        img: "CleanShot 2022-07-14 at 22.28.16@2x.jpg",
        description: "comic book art, marvel comics, dc comics",
        type: "toggle",
        variants: ["comic book art", "marvel comimcs", "dc comics"],
      },

      {
        title: "vintage disney",
        img: "CleanShot 2022-07-14 at 22.29.43@2x.jpg",
        description: "vintage disney",
        type: "toggle",
        variants: ["vintage disney"],
      },
      {
        title: "pixel art",
        img: "CleanShot 2022-07-14 at 22.30.11@2x.jpg",
        description: "pixel art",
        type: "toggle",
        variants: ["pixel art", "pixelated art"],
      },
      {
        title: "1970s grainy, vintage",
        suffix: " illustration",
        img: "CleanShot 2022-07-14 at 22.31.51@2x.jpg",
        description: "1970s grainy, vintage",
        type: "toggle",
        variants: ["1970s grainy, vintage"],
      },
      {
        title: "hanna barbera",
        img: "CleanShot 2022-07-14 at 22.32.37@2x.jpg",
        description:
          "Hanna Barbera, 1960s, Scooby Doo, Flintstones, Jetsons, etc",
        type: "toggle",
        variants: [
          "hanna barbera",
          "1960s",
          "Scooby Doo",
          "Flintstones",
          "Jetsons",
          "etc",
        ],
      },
      {
        title: "southpark",
        img: "CleanShot 2022-07-14 at 22.33.35@2x.jpg",
        description: "southpark, cartman",
        type: "toggle",
        variants: ["southpark", "cartman"],
      },
      {
        title: "simpsons",
        img: "CleanShot 2022-07-18 at 23.47.27@2x.jpg",
        description: "simpsons, homer simpson, marge simpson",
        type: "toggle",
        variants: ["simpsons", "homer simpson", "from the simpsons"],
      },
      {
        title: "spirited away",
        img: "CleanShot 2022-07-14 at 22.34.38@2x.jpg",
        description: "spirited away",
        type: "toggle",
        variants: ["spirited away", "hayayo miyazaki"],
      },
      {
        title: "family guy",
        img: "CleanShot 2022-07-14 at 22.35.33@2x.jpg",
        description: "family guy",
        type: "toggle",
        variants: ["family guy"],
      },
      {
        title: "adventure time",
        img: "CleanShot 2022-07-14 at 22.36.08@2x.jpg",
        description: "adventure time",
        type: "toggle",
        variants: ["adventure time"],
      },
      {
        title: "powerpuff girls",
        suffix: " (1998)",
        img: "CleanShot 2022-07-14 at 23.37.10@2x.jpg",
        description: "powerpuff girls",
        type: "toggle",
        variants: ["powerpuff girls"],
      },
      {
        title: "far side comic",
        suffix: " (1998)",
        img: "CleanShot 2022-07-14 at 22.41.40@2x.jpg",
        description: "far side comic",
        type: "toggle",
        variants: ["far side comic"],
      },
    ],
  },
  "Illustration - analog, colour": {
    title: "Illustration - analog, colour",
    description: "",
    prefix: " ",
    suffix: " ",
    items: [
      {
        title: "airbrush",
        img: "CleanShot 2022-07-14 at 21.56.33@2x.jpg",
        description: "airbrush",
        type: "toggle",
        variants: ["airbrush"],
      },
      {
        title: "crayon",
        img: "CleanShot 2022-07-14 at 21.50.33@2x.jpg",
        description: "crayon, kid using crayons",
        type: "toggle",
        variants: ["crayon", "kid using crayons"],
      },
      {
        title: "ballpoint pen",
        img: "CleanShot 2022-07-14 at 21.41.11@2x.jpg",
        description: "ballpoint pen style, ink",
        type: "toggle",
        variants: ["ballpoint pen", "ink"],
      },
      {
        title: "child drawing",
        img: "CleanShot 2022-07-14 at 21.51.09@2x.jpg",
        description: "child drawing, children drawing, kindergarten",
        type: "toggle",
        variants: ["child drawing", "children drawing", "kindergarten"],
      },
      {
        title: "acrylic on Canvas",
        img: "CleanShot 2022-07-14 at 21.51.48@2x.jpg",
        description: "acrylic on Canvas",
        type: "toggle",
        variants: ["acrylic on Canvas"],
      },
      {
        title: "watercolour",
        img: "CleanShot 2022-07-14 at 21.52.42@2x.jpg",
        description: "watercolour",
        type: "toggle",
        variants: ["watercolour"],
      },
      {
        title: "colored pencil",
        suffix: " detailed",
        img: "CleanShot 2022-07-14 at 21.53.16@2x.jpg",
        description: "colored pencil detailed",
        type: "toggle",
        variants: ["colored pencil detailed"],
      },
      {
        title: "oil painting",
        img: "CleanShot 2022-07-14 at 21.54.25@2x.jpg",
        description: "oil painting, oil on canvas",
        type: "toggle",
        variants: ["oil painting", "oil on canvas"],
      },
      {
        title: "Ukiyo-e",
        img: "CleanShot 2022-07-14 at 21.54.57@2x.jpg",
        description: "Ukiyo-e",
        type: "toggle",
        variants: ["Ukiyo-e"],
      },
      {
        title: "chinese watercolour",
        img: "CleanShot 2022-07-14 at 21.55.33@2x.jpg",
        description: "chinese watercolour",
        type: "toggle",
        variants: ["chinese watercolour"],
      },
      {
        title: "pastels",
        img: "CleanShot 2022-07-14 at 21.56.07@2x.jpg",
        description: "pastels",
        type: "toggle",
        variants: ["pastels"],
      },
    ],
  },
  "Illustration - analog, monochrome": {
    title: "Illustration - analog, monochrome",
    description: "prefixed with in the style of X",
    prefix: " ",
    suffix: " ",
    items: [
      {
        title: "Banksy",
        img: "CleanShot 2022-07-14 at 21.40.03@2x.jpg",
        description: "Banksy style, street art, stencil",
        type: "toggle",
        variants: ["Banksy", "street art", "stencil"],
      },
      {
        title: "Ballpoint pen",
        img: "CleanShot 2022-07-14 at 21.41.11@2x.jpg",
        description: "Ballpoint pen style, ink",
        type: "toggle",
        variants: ["ballpoint pen", "ink"],
      },
      {
        title: "Pencil sketch",
        img: "CleanShot 2022-07-14 at 21.42.52@2x.jpg",
        description: "Pencil sketch",
        type: "toggle",
        variants: ["pencil sketch"],
      },
      {
        title: "Pencil drawing",
        img: "CleanShot 2022-07-14 at 21.45.12@2x.jpg",
        description:
          "Pencil drawing, detailed pencil, hyper-detailed, very realistic",
        type: "toggle",
        variants: ["pencil drawing"],
      },
      {
        title: "Political cartoon",
        suffix: " from US newspaper",
        img: "CleanShot 2022-07-14 at 21.45.23@2x.jpg",
        description: "Political cartoon from U.S newspaper",
        type: "toggle",
        variants: ["political cartoon from US newspaper"],
      },
      {
        title: "charocal sketch",
        img: "CleanShot 2022-07-14 at 21.46.53@2x.jpg",
        description: "charocal sketch",
        type: "toggle",
        variants: ["charocal sketch"],
      },
      {
        title: "field journal",
        suffix: " line art",
        img: "CleanShot 2022-07-14 at 21.47.45@2x.jpg",
        description: "field journal line art",
        type: "toggle",
        variants: ["field journal line art"],
      },
      {
        title: "Colouring-in",
        suffix: " sheet",
        img: "CleanShot 2022-07-14 at 21.48.14@2x.jpg",
        description: "Colouring-in sheet",
        type: "toggle",
        variants: ["Colouring-in sheet"],
      },
      {
        title: "Etching",
        suffix: "",
        img: "CleanShot 2022-07-14 at 21.48.57@2x.jpg",
        description: "Etching",
        type: "toggle",
        variants: ["Etching"],
      },
    ],
  },
  "Illustration - instructional": {
    title: "Illustration - instructional",
    description: "",
    prefix: " ",
    suffix: " ",
    items: [
      {
        title: "blueprint",
        img: "CleanShot 2022-07-14 at 22.04.27@2x.jpg",
        description: "blueprint",
        type: "toggle",
        variants: ["blueprint"],
      },
      {
        title: "patent drawing",
        img: "CleanShot 2022-07-14 at 22.05.30@2x.jpg",
        description: "patent drawing",
        type: "toggle",
        variants: ["patent drawing"],
      },
      {
        title: "cutaway",
        img: "CleanShot 2022-07-14 at 22.06.00@2x.jpg",
        description: "cutaway",
        type: "toggle",
        variants: ["cutaway"],
      },
      {
        title: "IKEA manual",
        img: "CleanShot 2022-07-14 at 22.06.34@2x.jpg",
        description: "IKEA manual",
        type: "toggle",
        variants: ["IKEA manual"],
      },
      {
        title: "instruction manual",
        img: "CleanShot 2022-07-14 at 22.07.02@2x.jpg",
        description: "instruction manual",
        type: "toggle",
        variants: ["instruction manual"],
      },

      {
        title: "botanical illustration",
        img: "CleanShot 2022-07-14 at 22.07.32@2x.jpg",
        description: "botanical illustration",
        type: "toggle",
        variants: ["botanical illustration"],
      },
      {
        title: "mythological map",
        img: "CleanShot 2022-07-14 at 22.08.15@2x.jpg",
        description: "mythological map",
        type: "toggle",
        variants: ["mythological map"],
      },
      {
        title: "old encyclopedia",
        img: "CleanShot 2022-07-14 at 22.09.01@2x.jpg",
        description: "old encyclopedia",
        type: "toggle",
        variants: ["old encyclopedia"],
      },
      {
        title: "voynich manuscript",
        img: "CleanShot 2022-07-14 at 22.09.42@2x.jpg",
        description: "voynich manuscript",
        type: "toggle",
        variants: ["voynich manuscript"],
      },
      {
        title: "scientific diagram",
        img: "CleanShot 2022-07-14 at 22.10.26@2x.jpg",
        description: "scientific diagram",
        type: "toggle",
        variants: ["scientific diagram"],
      },
      {
        title: "voronoi diagram",
        img: "CleanShot 2022-07-14 at 22.11.06@2x.jpg",
        description: "voronoi diagram",
        type: "toggle",
        variants: ["voronoi diagram"],
      },
    ],
  },
  "Photography - Proximity": {
    title: "Photography - Proximity",
    description:
      "DALL•E interprets these pretty loosely, and often provides candidate from the 'neighbour' framing, e.g: a close-up prompt might get extreme close-ups and medium shots in the mix. in",
    prefix: " ",
    suffix: " ",
    items: [
      {
        title: "extreme close-up",
        img: "extreme_closeup.jpg",
        suffix: " shot",
        description:
          "Film still of a cackling man, bushy moustache, extreme close-up shot",
        type: "toggle",
        variants: ["extreme close-up"],
      },
      {
        title: "close-up shot",
        img: "closeup.jpg",
        description:
          "A close-up of a woman's face, captured in low light with a soft focus. There is a gentle pink hue to the image, and the woman's features are lightly blurred. Cinestill 800t. (Source.)",
        type: "toggle",
        variants: ["close-up shot"],
      },
      {
        title: "medium shot",
        img: "medium_shot.jpg",
        description:
          "Medium shot, mid-shot, waist shot (depicts subject from waist up)",
        type: "toggle",
        variants: ["medium shot", "mid-shot", "waist shot"],
      },
      {
        title: "long shot",
        img: "longshot.jpg",
        description:
          "Long shot, wide shot, full shot (shows full subject + surroundings)",
        type: "toggle",
        variants: ["long shot", "wide shot", "full shot"],
      },
      {
        title: "extreme long",
        suffix: " shot",
        img: "extreme_longshot.jpg",
        description:
          "Extreme long shot, extreme wide shot, X 'in the distance'",
        type: "toggle",
        variants: ["extreme long shot", "extreme wide shot"],
      },
    ],
  },
  "Photography - Angles": {
    title: "Photography - Angles",
    description:
      "Angles of Photography, can be combined with the 'Proximity' keywords",
    prefix: " ",
    suffix: " ",
    items: [
      {
        title: "overhead view",
        img: "overhead.jpg",
        description:
          "Overhead view, establishing shot, from above, high angle, crane shot",
        type: "toggle",
        variants: [
          "Overhead view",
          "establishing shot",
          "from above",
          "high angle",
          "crane shot",
        ],
      },
      {
        title: "low angle",
        img: "low_angle.jpg",
        description: "Low angle, from below, worms-eye-view",
        type: "toggle",
        variants: ["Low angle", "from below", "worms-eye-view"],
      },
      {
        title: "aerial view",
        img: "aerial.jpg",
        description: "Aerial view, birds eye view,drone photography",
        type: "toggle",
        variants: ["Aerial view", "birds eye view", "drone photography"],
      },
      {
        title: "titled frame",
        img: "tilted_frame.jpg",
        description: "Tilted frame, dutch angle, skewed shot",
        type: "toggle",
        variants: ["Tilted frame", "dutch angle", "skewed shot"],
      },
      {
        title: "over the shoulder",
        suffix: " shot",
        img: "over_the_shoulder.jpg",
        description: "Over the shoulder shot, from the side, angled shot",
        type: "toggle",
        variants: ["over the shoulder shot", "from the side", "angled shot"],
      },
    ],
  },
  "Photography - Lenses": {
    title: "Photography - Lenses",
    description:
      "Specific lenses have specific styles and features, and can be combined with the 'Angles' keywords",
    prefix: " ",
    suffix: " ",
    items: [
      {
        title: "fast shutter",
        img: "fast_shutter.jpg",
        description:
          "Fast shutter speed, high speed, action photo, 1/1000 sec shuttter",
        type: "toggle",
        variants: [
          "fast shutter speed",
          "high speed",
          "action photo",
          "1/1000 sec shutter",
        ],
      },
      {
        title: "long exposure",
        img: "slow_shutter.jpg",
        description:
          "Long Exposure, Slow shutter speed, low speed,long exposure slow motion, 1/100 sec shutter",
        type: "toggle",
        variants: [
          "long exposure",
          "slow shutter speed",
          "low speed",
          "long exposure slow motion",
          "1/100 sec shutter",
        ],
      },
      {
        title: "bokeh",
        img: "bokeh.jpg",
        description:
          "Bokeh, shallow depth of field, out of focus background, blurry background",
        type: "toggle",
        variants: [
          "bokeh",
          "shallow depth of field",
          "out of focus background",
          "blurry background",
        ],
      },
      {
        title: "tilt shift",
        img: "tiltshift.jpg",
        description: "tilt shift",
        type: "toggle",
        variants: ["tilt shift"],
      },
      {
        title: "motion blur",
        img: "motionblur.jpg",
        description: "You know what motion blur is",
        type: "toggle",
        variants: ["motion blur"],
      },
      {
        title: "telephoto lens",
        img: "telephoto.jpg",
        description:
          "Telephoto lens, shot from afar, feels 'voyeuristic', Sigma 500mm f/5",
        type: "toggle",
        variants: [
          "telephoto lens",
          "shot from afar",
          "feels 'voyeuristic'",
          "Sigma 500mm f/5",
        ],
      },
      {
        title: "Wide angle",
        siffix: " lens",
        img: "wide_angle.jpg",
        description: "Wide angle lens, 15mm",
        type: "toggle",
        variants: ["wide angle", "15mm"],
      },
      {
        title: "fish-eye",
        prefix: " ",
        siffix: " lens",
        img: "fish_eye.jpg",
        description: "Distorts the scene,wide angle, the center 'bulges'",
        type: "toggle",
        variants: ["wide angle", "15mm"],
      },
      {
        title: "deep depth",
        img: "fish_eye.jpg",
        description: "Deep depth of field, make all elements sharp",
        type: "toggle",
        variants: ["Deep depth of field", "make all elements sharp"],
      },
    ],
  },
  "Photography - Lightning prompts": {
    title: "Photography - Lightning prompts",
    description: "Add a lightning prompt to liven your DALL-E generated photos",
    prefix: " ",
    suffix: " lighting",
    items: [
      {
        title: "golden hour",
        img: "golden_hour.jpg",
        description:
          "Golden hour, dusk, sunset, sunrise - warm lighting, strong shadows",
        type: "toggle",
        variants: [
          "Golden hour",
          "dusk",
          "sunset",
          "sunrise",
          "warm lighting",
          "strong shadows",
        ],
      },
      {
        title: "blue hour",
        img: "blue_hour.jpg",
        description: "Blue hour, twilight, cool, ISO1200, slow shutter speed",
        type: "toggle",
        variants: [
          "Blue hour",
          "twilight",
          "cool",
          "ISO1200",
          "slow shutter speed",
        ],
      },
      {
        title: "midday",
        img: "midday.jpg",
        description: "Midday, noon, ISO100, ISO200, ISO400, ISO800",
        type: "toggle",
        variants: ["Midday", "noon", "ISO100", "ISO200", "ISO400", "ISO800"],
      },
      {
        title: "warm",
        img: "warm.jpg",
        description: "warm, 2700K",
        type: "toggle",
        variants: ["warm", "2700K"],
      },
      {
        title: "cold",
        img: "cold.jpg",
        description: "cold, fluorescent, 4800K",
        type: "toggle",
        variants: ["cold", "fluorescent", "4800K"],
      },
      {
        title: "flash photography",
        img: "flash_photo.jpg",
        description: "hash flash, flash photography, flash shot, flash shot",
        type: "toggle",
        variants: [
          "hash flash",
          "flash photography",
          "flash shot",
          "flash shot",
        ],
      },
      {
        title: "Purple and Yellow",
        img: "colorful.jpg",
        suffix: " lighting",
        description: "Define the colors, any two or thre color matchs will do",
        type: "toggle",
        variants: ["Purple and Yellow", "Blue and Orange", "Green and Red"],
      },
      {
        title: "high-key",
        prefix: " ",
        siffix: " lighting",
        img: "high_key.jpg",
        description:
          "High-key lighting, neutral, flat, even, corporate, professional, ambient",
        type: "toggle",
        variants: [
          "High-key ",
          "neutral",
          "flat",
          "even",
          "corporate",
          "professional",
          "ambient",
        ],
      },
      {
        title: "low-key",
        img: "low_key.jpg",
        description:
          "Low-key lighting, dramatic, single light source, high-contrast",
        type: "toggle",
        variants: [
          "Low-key ",
          "dramatic",
          "single light source",
          "high-contrast",
        ],
      },
      {
        title: "studio lighting",
        img: "studio.jpg",
        description:
          "Studio lighting, professional lighting. studio portrait, well-lit",
        type: "toggle",
        variants: ["Studio ", "professional ", "studio portrait", "well-lit"],
      },
    ],
  },

  "Photography - Famous photographer styles": {
    title: "Famous photographer style [adds in the style of...]",
    description:
      "DALL-E can generate a photo with the style of a famous photographer",
    prefix: ", in the style of ",
    suffix: " ",
    items: [
      {
        title: "Dorothea Lange",
        img: "dorothea_lange.jpg",
        description: "Dorothea Lange",
        type: "toggle",
        variants: ["Dorothea Lange"],
      },
      {
        title: "Eric Lafforgue",
        img: "CleanShot 2022-07-14 at 20.50.21@2x.jpg",
        description: "Eric Lafforgue",
        type: "toggle",
        variants: ["Eric Lafforgue"],
      },
      {
        title: "Annie Leibovitz",
        img: "CleanShot 2022-07-14 at 20.51.33@2x.jpg",
        description: "Annie Leibovitz",
        type: "toggle",
        variants: ["Annie Leibovitz"],
      },
      {
        title: "Steve McCurry",
        img: "CleanShot 2022-07-14 at 20.52.49@2x.jpg",
        description: "Lee Jeffries",
        type: "toggle",
        variants: ["Lee Jeffries"],
      },
      {
        title: "Lee Jeffries",
        img: "CleanShot 2022-07-14 at 20.53.24@2x.jpg",
        description: "Lee Jeffries",
        type: "toggle",
        variants: ["Lee Jeffries"],
      },
      {
        title: "Nancy Goldin",
        img: "CleanShot 2022-07-14 at 20.54.13@2x.jpg",
        description: "Nancy Goldin",
        type: "toggle",
        variants: ["Nancy Goldin"],
      },
      {
        title: "Yousuf Karsh",
        img: "CleanShot 2022-07-14 at 20.56.50@2x.jpg",
        description: "Yousuf Karsh",
        type: "toggle",
        variants: ["Yousuf Karsh"],
      },
      {
        title: "George Hurrell",
        img: "CleanShot 2022-07-14 at 20.57.31@2x.jpg",
        description: "George Hurrell",
        type: "toggle",
        variants: ["George Hurrell"],
      },
      {
        title: "Kenneth Willardt",
        img: "CleanShot 2022-07-14 at 20.58.28@2x.jpg",
        description: "Kenneth Willardt",
        type: "toggle",
        variants: ["Kenneth Willardt"],
      },

      {
        title: "Vivian Maier",
        img: "CleanShot 2022-07-14 at 21.00.46@2x.jpg",
        description: "Vivian Maier",
        type: "toggle",
        variants: ["Vivian Maier"],
      },
    ],
  },
};
