# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.6.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
      # read npm versio from package.json
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
    - name: zip-build-output
      uses: vimtor/action-zip@v1
      with:
        files: dist/
        dest: 'dalle-chrome-ext.v${{ inputs.version }}.zip'
    - uses: actions/upload-artifact@v3
      with:
        name: 'artifact-dalle-chrome-ext.v${{ inputs.version }}.zip'
        path: 'dalle-chrome-ext.v${{ inputs.version }}.zip'
