# This is a basic workflow to help you get started with Actions

name: Publish to chrome webstore

# Controls when the workflow will run
on:
  release:
    types: [prereleased, released]

env:
  RELEASE_VERSION: ${{ github.event.release.tag_name }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build: 
    uses: ./.github/workflows/build-reusable-workflow.yml

  publish-to-chrome-webstore:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v3
        id: download
        name: 'Try to download the artifact from previous builds'
        with:
          name: 'artifact-dalle-chrome-ext.v${{ github.event.release.tag_name }}.zip'
      
      - name: Upload & release
        uses: mnao305/chrome-extension-upload@3.0.0
        with:
          file-path: '${{steps.download.outputs.download-path}}/dalle-chrome-ext.v${{ github.event.release.tag_name }}.zip'
          extension-id: 'hjhagfbhighhchddcbejligbanloandc'
          client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          publish: ${{ !github.event.release.prerelease }}
